import "./globals.css";

import { Providers } from "./providers";
import AppNavbarSessionProvider from "./1AppComponents/AppNavbarSessionProvider";
import { nunitoSans } from "./fonts";

export const metadata = {
	title: "Kitten Sanctuary Singapore",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className="light">
			<body className={`${nunitoSans.className} antialiased`}>
				<Providers>
					<AppNavbarSessionProvider />
					{children}
				</Providers>
			</body>
		</html>
	);
}
